services:

  hapi-fhir:
    image: hapiproject/hapi:latest
    container_name: hapi-fhir

    ports:
      - "8080:8080"

    restart: unless-stopped

    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://hapi-postgres:5432/hapi"
      SPRING_DATASOURCE_USERNAME: "admin"
      SPRING_DATASOURCE_PASSWORD: "admin"
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
      HIBERNATE_DIALECT: "ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgresDialect"

    depends_on:
      hapi-postgres:
        condition: service_healthy


  hapi-postgres:
    image: postgres:16-alpine
    container_name: hapi-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: "hapi"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"

    volumes:
      - hapi-postgres-data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U admin -d hapi"
        ]
      interval: 10s
      timeout: 5s
      retries: 5


  airflow-postgres:
    image: postgres:16-alpine
    container_name: airflow-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: "airflow"
      POSTGRES_USER: "airflow"
      POSTGRES_PASSWORD: "airflow"

    volumes:
      - airflow-postgres-data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U airflow -d airflow"
        ]
      interval: 10s
      timeout: 5s
      retries: 5


  airflow-init:
    build:
      context: .
      dockerfile: Dockerfile.airflow

    container_name: airflow-init

    depends_on:
      airflow-postgres:
        condition: service_healthy

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow"
      AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
      AIRFLOW__API_AUTH__JWT_SECRET: "healthcare-ai-local-jwt-secret"
      FHIR_BASE_URL: "http://hapi-fhir:8080/fhir"
      PYTHONPATH: "/opt/airflow/project/src"
      _AIRFLOW_DB_MIGRATE: "true"
      _AIRFLOW_WWW_USER_CREATE: "true"
      _AIRFLOW_WWW_USER_USERNAME: "airflow"
      _AIRFLOW_WWW_USER_PASSWORD: "airflow"


    command: version


  airflow-api-server:
    build:
      context: .
      dockerfile: Dockerfile.airflow

    container_name: airflow-api-server

    restart: unless-stopped

    depends_on:
      airflow-postgres:
        condition: service_healthy


    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow"
      AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_USERS: "airflow:admin"
      PYTHONPATH: "/opt/airflow/project/src"
      AIRFLOW__CORE__EXECUTION_API_SERVER_URL: "http://airflow-api-server:8080/execution/"
      AIRFLOW__API_AUTH__JWT_SECRET: "healthcare-ai-local-jwt-secret"

    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./src:/opt/airflow/project/src
      - ./data:/opt/airflow/project/data


    ports:
      - "8081:8080"

    command: api-server


  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow

    container_name: airflow-scheduler

    restart: unless-stopped

    depends_on:
      airflow-postgres:
        condition: service_healthy

    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow"
      AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
      AIRFLOW__CORE__EXECUTION_API_SERVER_URL: "http://airflow-api-server:8080/execution/"
      AIRFLOW__API_AUTH__JWT_SECRET: "healthcare-ai-local-jwt-secret"
      FHIR_BASE_URL: "http://hapi-fhir:8080/fhir"
      PYTHONPATH: "/opt/airflow/project/src"

    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./src:/opt/airflow/project/src
      - ./data:/opt/airflow/project/data

    command: scheduler


  airflow-dag-processor:
    build:
      context: .
      dockerfile: Dockerfile.airflow

    container_name: airflow-dag-processor

    restart: unless-stopped

    depends_on:
      airflow-postgres:
        condition: service_healthy
    
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow"
      AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
      AIRFLOW__CORE__EXECUTION_API_SERVER_URL: "http://airflow-api-server:8080/execution/"
      FHIR_BASE_URL: "http://hapi-fhir:8080/fhir"
      PYTHONPATH: "/opt/airflow/project/src"

    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./src:/opt/airflow/project/src
      - ./data:/opt/airflow/project/data

    command: dag-processor


volumes:
  hapi-postgres-data:
  airflow-postgres-data: